name: Screenshot
on: [push]
jobs:
  clojure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '16'
      - name: Do it
        shell: bash
        run: |
          set -e
          curl -L -o bb.tar.gz "https://github.com/babashka/babashka/releases/download/v0.7.3/babashka-0.7.3-linux-amd64-static.tar.gz"
          tar -xvzf bb.tar.gz
          chmod +x bb
          ./bb bb_main.clj
      - name: upload screenshot
        uses: actions/upload-artifact@v2
        with:
          name: screenshot
          path: artifact/screenshot


          
